- pom.xml
- src/main/java/org/apache/sling/resourceresolver/impl/CommonResourceResolverFactoryImpl.java
- src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverFactoryImpl.java
- src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverImpl.java
This is the other half of the API changes necessary for fixing SLING-3524. There are two related pull requests to implement a full fix. To avoid repeating myself, I'll update the corresponding JIRA ticket with the reasoning, and with the links of the other requests.
> SLING-3524: Allow distinguishing cloning from normal login in providers.

- src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverImpl.java
- src/test/java/org/apache/sling/resourceresolver/impl/MockedResourceResolverImplTest.java
find the difference of the redundant occurrences vs actual tokens of delimiter ( slash '/ ')
> SLING-8341 : find extra slashes and ignore redundant delimiteres

- src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverImpl.java
empty path should map to root instead of a null resource.
> SLING-8349 : resolver.map - map empty path to root path

- src/main/java/org/apache/sling/resourceresolver/impl/providers/ResourceProviderTracker.java
- src/test/java/org/apache/sling/resourceresolver/impl/providers/ResourceProviderTrackerTest.java
This change calls the same logic that is applied for ResourceProviderHandlers when a ResourceChangeListener is registered after a ResourceProvider got either activated or deactivated.
> SLING-8946 non deterministic resource observation

- src/main/java/org/apache/sling/resourceresolver/impl/providers/ResourceProviderTracker.java
- src/test/java/org/apache/sling/resourceresolver/impl/providers/ResourceProviderTrackerTest.java
When a new ResourceProviderHandler gets activated or an existing one deactivated currently all other registered ResourceProviderHandlers get updated. To keep the exclude paths set for resource observation consistent it is sufficient to only update those that are actually overlapping.
> SLING-9040 only update intersecting ResourceProviderHandler

- src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverFactoryActivator.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/test/java/org/apache/sling/resourceresolver/impl/MockedResourceResolverImplTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/MapEntriesTest.java
see https://issues.apache.org/jira/browse/SLING-10167
> SLING-10167 Ensure only valid absolute paths (not ending with "/") are used in JCR queries for loading existing aliases on startup

- bnd.bnd
- pom.xml
- src/main/java/org/apache/sling/resourceresolver/impl/CommonResourceResolverFactoryImpl.java
- src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverFactoryActivator.java
- src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverMetrics.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/test/java/org/apache/sling/resourceresolver/impl/EtcMappingResourceResolverTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/ResourceResolverMetricsTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/AbstractMappingMapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/EtcMappingMapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/MapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/ResourceMapperImplTest.java
Currently we are quite short in terms of metrics, which allow us to observe some basic numbers for the ResourceResolver. This PR adds 3 basic metrics:
* total number of aliases
* total number of vanity paths
* the number of unclosed resourceResolvers (since the last restart of the RR bundle)
The implementation is straight forward, there is a single ```ResourceResolverMetrics``` service, which either registers the Gauge services into OSGI or directly uses the Counter from Sling Commons Metrics. Basic test coverage for the ```ResourceResolverMetrics``` is provided, but I haven't augmented the existing test cases with validations, that their operations properly reflect in the metrics.
I tested this PR locally with my AEM instance, and all 3 metrics are reflected as JMX objects:
* …
> SLING-10945 add metrics

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntry.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/ResourceMapperImpl.java
- src/test/java/org/apache/sling/resourceresolver/impl/MockedResourceResolverImplTest.java
In this change we make sure that the `MapEntries` are properly populated when constructing the unit under test. This caused the `testMapping()` test to fail in `MapEntries#replace()` for 
```
// applied MapEntry: /content.html-/$
java.lang.IllegalArgumentException: Illegal group reference: group index is missing
at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1030)
at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:998)
at java.base/java.util.regex.Matcher.replaceFirst(Matcher.java:1408)
at org.apache.sling.resourceresolver.impl.mapping.MapEntry.replace(MapEntry.java:301)
at org.apache.sling.resourceresolver.impl.mapping.ResourceMapperImpl.populateMappingsFromMapEntries(ResourceMapperImpl.java:267)
at …
```
> SLING-11138: run MockedResourceResolverImplTest with MapEntries populated

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/ResourceMapperImpl.java
The final effort to return at least one mapped path should handle the case when the user does
not have read access to the root path.
> SLING-10844 - ResourceMapper.getMapping() returns null for empty path

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/ResourceMapperImpl.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/ResourceMapperImplTest.java
> SLING-11757: resource resolver: pathless URL in vanity path causes NPE in ResourceMapperImpl.apply()

- pom.xml
- src/main/java/org/apache/sling/resourceresolver/impl/FactoryRegistrationHandler.java
- src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverFactoryActivator.java
- src/test/java/org/apache/sling/resourceresolver/impl/FactoryRegistrationHandlerTest.java
- src/test/java/org/apache/sling/resourceresolver/util/CustomMatchers.java
- src/test/java/org/apache/sling/resourceresolver/util/events/AbstractAwaitingListener.java
- src/test/java/org/apache/sling/resourceresolver/util/events/RecordingListener.java
- src/test/java/org/apache/sling/resourceresolver/util/events/ServiceEventUtil.java
- src/test/resources/junit-platform.properties
- reworked synchronization from relying on worker queue to locks
- increased test coverage, particularly for concurrent scenarios
- switched to junit-platform to allow mixing junit4 and junit5 tests
- enabled parallel test execution for junit-platform
> SLING-12019 - Avoid duplicate ResourceResolverFactory registrations

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/InMemoryResourceProvider.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/MapEntriesTest.java
Changes query strategy for sling:alias to the same as sling:vanityPath.
Fallbacks allow deploying on older store versions or on stores that require an index on "first(sling:alias)".
> SLING-11799: ResourceResolver - use keyset pagination for sling:alias query

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
sample output:
~~~
09.01.2024 17:47:51.581 *INFO* [ResourceResolverFactory registration] org.apache.sling.resourceresolver.impl.mapping.MapEntries alias initialization - end, processed 134066 resources with sling:alias properties in 34040ms (~3938 resource/s)
09.01.2024 17:47:51.654 *INFO* [VanityPathInitializer] org.apache.sling.resourceresolver.impl.mapping.MapEntries vanity path initialization - end, processed 47 resources with sling:vanityPath properties in 43ms (~1083 resource/s)
~~~
> SLING-12222: INFO-level log not only query time but also # of resources (and rate) for sling:alias and sling:vanityPath

- src/test/java/org/apache/sling/resourceresolver/impl/mapping/MapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/PathGeneratorTest.java
This just increases test coverage, with no assumptions whether the observed behavior is actually correct.
> SLING-12412: ResourceResolver: add test coverage for empty aliases, blank aliases, and invalid aliases

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/MapEntryIteratorTest.java
1. Untangle MapIterator from MapEntries for better testability from unit tests
2. Add unit tests
> Resource Resolver: refactor MapEntries - improve MapIterator test coverage

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/MapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/VanityPathMapEntriesTest.java
1. in MapEntries: move most vanity path related code into a single place for later refactoring
2. Move vanity path related tests into separate test class
3. Code cleanup in test cases
Note that line coverage warning is due to code being moved around in MapEntries. Test coverage for vanity paths will be improved when factored out into a separate class.
> SLING-12632: move all (only) vanity path related code in a single place

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
Currently, resolveMapsMap is initialized as immutable singleton map containing a mapping of GLOBAL_LIST_KEY to an empty list.
Later on, during alias init, it is changed to a ConcurrentHashMap and it then immediately gets populated with a mapping for that key. For [SLING-9782](https://issues.apache.org/jira/browse/SLING-9782) this was changed to init the Map even if the ("optimized") alias init fails.
Rather than that, let's always init the map as writeable map, which also allows to make it final (which will help with future refactorings).
> SLING-12651: avoid re-assignment of resolveMapsMap

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/MapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/VanityPathMapEntriesTest.java
Move into standalone class will be next step; this is supposed to make review easier.
> SLING-12648: MapEntries: factor out vanity path handling into inner class

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/VanityPathHandler.java
1. Renames variables/parameters for clarity
2. fixes whitespace
3. simplifies code
4. extract sub methods when nested too deeply
5. removes the magic number "2" when counting cached map entries for vanity paths
6. other minor Sonar complaints
> SLING-12666: VanityPathHandler, address warnings, refactor

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
`` this.metrics.get().setNumberOfResourcesWithAliasesOnStartupSupplier`` is called twice (first with correct supplier, then with a wrong one)
also sort the counters by (a) category and (b) by name.
> SLING-12679: fix incorrect metrics init

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/AbstractMappingMapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/AliasMapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/EtcMappingMapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/MapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/StringInterpolationMapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/VanityPathMapEntriesTest.java
@joerghoh - you will have to trust me on this one; Spotless insists of re-indenting.
The changes are the same as in https://github.com/apache/sling-org-apache-sling-resourceresolver/compare/1.x...SLING-12701.
> SLING-12701: Resource Resolver: MapEntries - move alias handling into inner class

- src/main/java/org/apache/sling/resourceresolver/impl/providers/ResourceProviderTracker.java
- src/test/java/org/apache/sling/resourceresolver/impl/providers/ResourceProviderTrackerTest.java
This PR fixes following exception observed during unregistration of resource provider:
```
[FelixLogListener] Events.Framework.org.apache.sling.resourceresolver FrameworkEvent ERROR (java.lang.NullPointerException: Cannot invoke "org.apache.sling.resourceresolver.impl.providers.ResourceProviderHandler.isUsed()" because "deactivateHandler" is null)
java.lang.NullPointerException: Cannot invoke "org.apache.sling.resourceresolver.impl.providers.ResourceProviderHandler.isUsed()" because "deactivateHandler" is null
at org.apache.sling.resourceresolver.impl.providers.ResourceProviderTracker.remove(ResourceProviderTracker.java:301) 
at org.apache.sling.resourceresolver.impl.providers.ResourceProviderTracker.unregister(ResourceProviderTracker.java:202) 
at …
```
> SLING-12741 - NPE resource resolver during resource provider unregisteration

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/AliasHandler.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/AliasMapEntriesTest.java
- `AliasHandler.initializeAliases()` returns void now, as the return value was misleading anyway. It has been replaced by `AliasHandler.usesCache()`, indicating the Maps have been initialized.
- Make sure that the `AliasHandler.aliasMapsMap` is always non-null.
This also aligns Alias init with VP init.
> SLING-12763: cleanup API of AliasHandler wrt 'optimized resolution'

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/AliasHandler.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/ResourceMapperImpl.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/AliasMapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/ResourceMapperImplTest.java
This removes logic from `ResourceMapperImpl` that previously took two different code paths, depending on the mode.
To get there, `AliasHandler` now handles `getAliasMap` even when the alias cache is not in use.
Note: for that, it uses its own resolver instance, thus the test in `ResourceMapperImplTest` does not "work" anymore (code removed for now). Suggestions how to resurrect that check (do we even need it anymore?) are welcome.
> SLING-12777: alias refactoring - make ResourceMapperImpl ignorant of optimimized/non-optimized case

- src/main/java/org/apache/sling/resourceresolver/impl/ResourceResolverImpl.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/ResourceMapperImpl.java
- src/test/java/org/apache/sling/resourceresolver/impl/MockedResourceResolverImplTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/ResourceDecorationTest.java
This changes `ResourceMapperImpl.resolveAliases` to use the `Resource` that it already has for (a) getting the aliases and (b) walking the tree up.
Changes in tests unfortunately were needed as:
- resources were mocked without handling `getParent()`, and
- decorator tests were using inconsistent mocked values for `getParent()` and `getName()`
> SLING-12787: ResourceResolver: alias refactoring - use Resource instead of Path when getting aliases

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/AliasHandler.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/AliasMapEntriesTest.java
This mainly improves test coverage wrt what queries are used, and how `AliasHandler` handles exceptions.
It also adds test coverage for the "uncached" case (where no query is generated at all, instead the Sling resource tree is walked).
This also includes two minor refactorings in `AliasHandler`.
> SLING-12804: alias refactoring - improve test coverage of query statements

- src/test/java/org/apache/sling/resourceresolver/impl/mapping/AliasMapEntriesTest.java
This parametrizes the test class to run with "optimized" on/off.
Several tests only make sense when running in "optimized" node, thus they are skipped to the other mode.
Also some more cleanup.
>  SLING-12888: Parametrize AliasMapEntriesTest for optimized/non-optimized testing

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/AliasHandler.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/VanityPathHandler.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/AliasMapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/MapEntriesTest.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/VanityPathMapEntriesTest.java
Code consistent with vanity path handling; MapEntries needed to be updated for two separate queues.
> SLING-12894: alias refactoring - support observation events while bg init not finished

- src/main/java/org/apache/sling/resourceresolver/impl/mapping/AliasHandler.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/MapEntries.java
- src/main/java/org/apache/sling/resourceresolver/impl/mapping/VanityPathHandler.java
- src/test/java/org/apache/sling/resourceresolver/impl/mapping/MapEntriesTest.java
also
- adds utility method
- changes the map entries and handler classes to use it throughout
> SLING-12917: ResourceResolver: alias refactoring - log elapsed time for draining observation queue
